# Generated by Django 5.2.7 on 2025-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('ip', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('logid', models.TextField(blank=True, null=True)),
                ('log_description', models.TextField(blank=True, db_column='log_descripcion', null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('usuario', models.TextField(blank=True, null=True)),
                ('dispositivo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IP en blacklist',
                'verbose_name_plural': 'IPs en blacklist',
                'db_table': 'agent"."ip_blacklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('ip', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='IP')),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('ciudad', models.TextField(blank=True, null=True)),
                ('isp', models.TextField(blank=True, null=True)),
                ('organizacion', models.TextField(blank=True, null=True)),
                ('cliente', models.TextField(blank=True, null=True)),
                ('mobile', models.TextField(blank=True, null=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IP Whitelist',
                'verbose_name_plural': 'IP Whitelist',
                'db_table': 'agent"."ip_whitelist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramSolicitud',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('chat_id', models.CharField(blank=True, db_column='Chat_ID', max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=255, null=True)),
                ('empresa', models.CharField(blank=True, db_column='Empresa', max_length=255, null=True)),
                ('solicitud', models.TextField(blank=True, db_column='Solicitud', null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, db_column='Fecha_Solicitud', null=True)),
            ],
            options={
                'db_table': 'telegram"."solicitudes',
                'ordering': ['-fecha_solicitud'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantCredentials',
            fields=[
                ('tenant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tenant_name', models.TextField(unique=True)),
                ('alarms_one_id', models.TextField(blank=True, null=True)),
                ('logs360siem_id', models.TextField(blank=True, null=True)),
                ('site24x7_id', models.TextField(blank=True, null=True)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('first_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Tenant credentials',
                'verbose_name_plural': 'Tenant credentials',
                'db_table': 'agent"."tenant_credentials',
                'managed': False,
            },
        ),
    ]
