# Generated by Django 5.2.7 on 2025-12-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantCredentials',
        ),
    ]
