# Generated by Django 5.2.7 on 2025-12-11 13:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_tenantcredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistCountryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paises', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Preferencia de países de whitelist',
                'verbose_name_plural': 'Preferencias de países de whitelist',
                'db_table': 'agent"."whitelist_country_preference',
                'managed': False,
            },
        ),
    ]
