# Generated by Django 5.2.7 on 2025-12-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_whitelist_pref_drop_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistcountrypreference',
            options={'verbose_name': 'Whitelist Country Preference', 'verbose_name_plural': 'Whitelist Country Preferences'},
        ),
    ]
