# Generated by Django 5.2.7 on 2025-12-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_whitelistcountrypreference_options'),
        ('tenants', '0024_alter_notificationchannelpreference_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistcountrypreference',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_country_preference', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='whitelistcountrypreference',
            name='paises',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='whitelistcountrypreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='whitelistcountrypreference',
            table='whitelist_country_preference',
        ),
    ]
