# Generated by Django 5.2.7 on 2025-12-23 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0024_alter_notificationchannelpreference_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoarTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_id', models.TextField(db_index=True)),
                ('dispositivo', models.TextField(blank=True, default='')),
                ('tipo_de_amenaza', models.TextField(blank=True, default='')),
                ('nivel_de_severidad', models.TextField(blank=True, default='')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('descripcion_incidente', models.TextField(blank=True, default='')),
                ('analisis_criticidad', models.TextField(blank=True, default='')),
                ('medidas_correctivas', models.TextField(blank=True, default='')),
                ('resumen_humano', models.TextField(blank=True, default='')),
                ('riesgo_detectado', models.TextField(blank=True, default='')),
                ('application', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], db_index=True, default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soar_assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soar_closed_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soar_created_tickets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soar_tickets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'agent"."soar_ticket',
                'indexes': [models.Index(fields=['tenant', 'status'], name='idx_soar_ticket_tenant_status'), models.Index(fields=['tenant', 'alarm_id'], name='idx_soar_ticket_tenant_alarm')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('tenant', 'alarm_id'), name='uniq_open_ticket_per_alarm_tenant')],
            },
        ),
    ]
