# Generated by Django 5.2.7 on 2025-12-30 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soar_tickets', '0002_soarticket_initial_notes'),
        ('tenants', '0029_alter_tenantdashboardembed_eventos_diarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soarticket',
            name='reminder_due_soon_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soarticket',
            name='reminder_due_soon_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soarticket',
            name='reminder_due_soon_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='soarticket',
            index=models.Index(fields=['status', 'due_date'], name='idx_soar_ticket_status_due'),
        ),
    ]
