# Generated by Django 5.2.7 on 2026-01-13 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soar_tickets', '0003_soarticket_reminder_due_soon_count_and_more'),
        ('tenants', '0031_alter_tenants_contracts_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soarticket',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se notificó por primera (y única) vez el vencimiento del ticket.', null=True),
        ),
        migrations.AddField(
            model_name='soarticket',
            name='overdue_notified_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soarticket',
            name='reminder_due_soon_for',
            field=models.DateField(blank=True, help_text="Para qué due_date ya se envió recordatorio 'vence en 2 días'.", null=True),
        ),
        migrations.AddIndex(
            model_name='soarticket',
            index=models.Index(fields=['status', 'due_date', 'overdue_notified_at'], name='idx_soar_ticket_overdue_scan'),
        ),
    ]
