# Generated by Django 5.2.7 on 2025-11-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenteSOAR',
            fields=[
                ('alarmd_id', models.CharField(db_column='alarmd_id', max_length=255, primary_key=True, serialize=False)),
                ('aotag', models.CharField(blank=True, db_column='aotag', max_length=255, null=True)),
                ('dispositivo', models.CharField(blank=True, db_column='dispositivo', max_length=255, null=True)),
                ('descripcion_incidente', models.TextField(blank=True, db_column='descripcion_incidente', null=True)),
                ('tipo_de_amenaza', models.CharField(blank=True, db_column='tipo_de_amenaza', max_length=255, null=True)),
                ('nivel_de_severidad', models.CharField(blank=True, db_column='nivel_de_severidad', max_length=255, null=True)),
                ('medidas_correctivas', models.TextField(blank=True, db_column='medidas_correctivas', null=True)),
                ('resumen_humano', models.TextField(blank=True, db_column='resumen_humano', null=True)),
                ('riego_detectado', models.CharField(blank=True, db_column='riego_detectado', max_length=255, null=True)),
                ('analisis_criticidad', models.TextField(blank=True, db_column='analisis_criticidad', null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('time', models.TimeField(blank=True, db_column='time', null=True)),
                ('application', models.CharField(blank=True, db_column='Application', max_length=255, null=True)),
            ],
            options={
                'db_table': 'agent"."incidentes_soar',
                'managed': False,
            },
        ),
    ]
