"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from celery.schedules import crontab
import sys
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY=os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

ALLOWED_HOSTS = ['ia.inntesec.com', 'www.ia.inntesec.com', '127.0.0.1:8001','127.0.0.1:8000', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://ia.inntesec.com', 'https://www.ia.inntesec.com', 'http://127.0.0.1:8001','http://127.0.0.1:8000']

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"
ALARMSONE_ACCESS_TOKEN = os.getenv("ALARMSONE_ACCESS_TOKEN")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # necesario para django-two-factor-auth
    'django.contrib.sites',

    # 2FA (OTP)
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',

    'inyeccion_api',
    'dashboard',
    'integrations',
#    'csp',
    'accounts',
    'soar_dashboard',
    'soar_incidents',
    'home',
    'siem',
    'site24x7',
    'tenants.apps.TenantsConfig',
    'soar_tickets',
]

SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'tenants.middleware.ActiveTenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
#    'csp.middleware.CSPMiddleware',
]

# === Content Security Policy ===
#CONTENT_SECURITY_POLICY = {
#    "DIRECTIVES": {
#        "default-src": ("'self'",),
#        "font-src": ("'self'",),
#        "img-src": ("'self'",),
#        "object-src": ("'none'",),
#        "script-src": ("'self'",),
#        "style-src": ("'self'",),
#        "frame-ancestors": ("'none'",),
#        "connect-src": (
#            "'self'",
#            "https://iaproductivo.inntesec.cl",
#            "https://alarmsone.manageengine.com",
#        ),
#    }
#}

# === Seguridad Django ===

# Fuerza HTTPS
#SECURE_SSL_REDIRECT = not DEBUG

# HSTS - indica al navegador usar solo HTTPS
#SECURE_HSTS_SECONDS = 31536000
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#SECURE_HSTS_PRELOAD = False

# Evita que el navegador interprete tipos MIME incorrectos
#SECURE_CONTENT_TYPE_NOSNIFF = True

# Bloquea iframes externos (clickjacking)
#X_FRAME_OPTIONS = 'DENY'

# Cookies seguras y con políticas de restricción
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'


ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [{
  "BACKEND": "django.template.backends.django.DjangoTemplates",
  "DIRS": [BASE_DIR / "templates"], 
  "APP_DIRS": True,
  "OPTIONS": {"context_processors": [
      "django.template.context_processors.request",
      "django.contrib.auth.context_processors.auth",
      "django.contrib.messages.context_processors.messages",
  ]},
}]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'portal_db',
        'USER': 'inntesec_ai',
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': 'localhost', 
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ES'

# Chile (maneja DST). NO usar 'UTC' aquí si quieres ver hora local en Django.
TIME_ZONE = "America/Santiago"

USE_I18N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # carpeta principal
    os.path.join(BASE_DIR, 'dashboard', 'static'),  # ejemplo de app
    os.path.join(BASE_DIR, 'soar_dashboard', 'static'),     # ejemplo de app
    os.path.join(BASE_DIR, 'soar_incidents', 'static'),     # ejemplo de app
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-dashboard-cache",
        "TIMEOUT": 300,  # segundos (puedes dejarlo None = infinito)
    }
}



# Configuración de Celery
# === Celery Config ===
CELERY_BROKER_URL = "redis://localhost:6379/0"        
CELERY_RESULT_BACKEND = "redis://localhost:6379/1"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Santiago"
CELERY_ENABLE_UTC = False

AUTH_USER_MODEL = 'tenants.TenantUser'

AUTHENTICATION_BACKENDS = [
    'tenants.auth_backends.TenantBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },

    "root": {  # logger raíz
        "handlers": ["console"],
        "level": "INFO",
    },

    "loggers": {
        # Logger específico para tu app 'home'
        "home": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "home.views": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # <<< AÑADE ESTO PARA VER inyeccion_api >>>
        "inyeccion_api": {
            "handlers": ["console"],
            "level": "DEBUG",   # así ves info/warning/debug de utils.py
            "propagate": False,
        },
    },
}

# ============================================
# CONFIGURACIÓN MICROSOFT GRAPH (OAuth2)
# ============================================

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Variables base (desde entorno)
MS_TENANT_ID = os.getenv("MS_TENANT_ID", "").strip()
MS_CLIENT_ID = os.getenv("MS_CLIENT_ID", "").strip()
MS_CLIENT_SECRET = os.getenv("MS_CLIENT_SECRET", "").strip()
MS_USER_EMAIL = os.getenv("MS_USER_EMAIL", "").strip()  # ej: ia@inntesec.com
MS_REDIRECT_URI = os.getenv("MS_REDIRECT_URI", "").strip()

# Evitar f-string con None o vacío
if MS_TENANT_ID:
    MS_TOKEN_URL = f"https://login.microsoftonline.com/{MS_TENANT_ID}/oauth2/v2.0/token"
else:
    MS_TOKEN_URL = "https://login.microsoftonline.com/common/oauth2/v2.0/token"

# Diccionario consolidado (seguro)
OAUTH2_MICROSOFT = {
    "MS_TOKEN_URL": MS_TOKEN_URL,
    "MS_CLIENT_ID": MS_CLIENT_ID,
    "MS_CLIENT_SECRET": MS_CLIENT_SECRET,
    "MS_USER_EMAIL": MS_USER_EMAIL,
}

# Indica a Django que confíe en Nginx cuando marca HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Fuerza que todo el tráfico sea HTTPS
#SECURE_SSL_REDIRECT = True
SECURE_SSL_REDIRECT = not DEBUG

# Asegura cookies seguras
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Retell AI
RETELL_API_KEY = os.getenv("RETELL_API_KEY", "").strip()
RETELL_AGENT_ID = os.getenv("RETELL_AGENT_ID", "").strip()
RETELL_TIMEOUT = int(os.getenv("RETELL_TIMEOUT", "20").strip())
