# Generated by Django 5.2.7 on 2026-01-02 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0029_alter_tenantdashboardembed_eventos_diarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('activity_items', models.JSONField(blank=True, default=list)),
                ('framework', models.CharField(blank=True, default='ISO27001', max_length=60)),
                ('framework_version', models.CharField(blank=True, default='2022', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance"."compliance_control',
                'indexes': [models.Index(fields=['domain', 'category'], name='compliance__domain_904535_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('level', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_risks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'compliance"."compliance_risk',
            },
        ),
        migrations.CreateModel(
            name='ComplianceTenantControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_evaluated', 'No evaluado'), ('not_implemented', 'No implementado'), ('in_progress', 'En proceso'), ('implemented', 'Implementado'), ('na', 'No aplica')], default='not_evaluated', max_length=30)),
                ('justification', models.TextField(blank=True, default='')),
                ('responsible_label', models.CharField(blank=True, default='', max_length=255)),
                ('primary_risk_code', models.CharField(blank=True, default='', max_length=50)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('last_review_at', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('alert', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_controls', to='compliance.compliancecontrol')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_compliance_controls', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_controls', to='tenants.tenant')),
            ],
            options={
                'db_table': 'compliance"."compliance_tenant_control',
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='link', max_length=30)),
                ('uri', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='compliance.compliancetenantcontrol')),
            ],
            options={
                'db_table': 'compliance"."compliance_evidence',
            },
        ),
        migrations.CreateModel(
            name='ComplianceTenantControlRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancerisk')),
                ('tenant_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancetenantcontrol')),
            ],
            options={
                'db_table': 'compliance"."compliance_tenant_control_risks',
            },
        ),
        migrations.AddField(
            model_name='compliancetenantcontrol',
            name='risks',
            field=models.ManyToManyField(blank=True, related_name='controls', through='compliance.ComplianceTenantControlRisk', to='compliance.compliancerisk'),
        ),
        migrations.AddConstraint(
            model_name='compliancerisk',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_compliance_risk_by_tenant'),
        ),
        migrations.AddConstraint(
            model_name='complianceevidence',
            constraint=models.UniqueConstraint(fields=('tenant_control', 'uri'), name='uniq_evidence_uri_by_control'),
        ),
        migrations.AddConstraint(
            model_name='compliancetenantcontrolrisk',
            constraint=models.UniqueConstraint(fields=('tenant_control', 'risk'), name='uniq_tc_risk'),
        ),
        migrations.AddIndex(
            model_name='compliancetenantcontrol',
            index=models.Index(fields=['tenant', 'status'], name='compliance__tenant__1d6d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancetenantcontrol',
            index=models.Index(fields=['tenant', 'applicable'], name='compliance__tenant__894787_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancetenantcontrol',
            constraint=models.UniqueConstraint(fields=('tenant', 'control'), name='uniq_tenant_control'),
        ),
    ]
