# Generated by Django 5.2.7 on 2025-10-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre de la empresa (campo 'Empresa' de la API)", max_length=255, unique=True)),
                ('alarms_one_id', models.IntegerField(blank=True, help_text='ID de AlarmsOne', null=True)),
                ('logs360siem_id', models.IntegerField(blank=True, help_text='ID de Logs360SIEM', null=True)),
                ('site24x7_id', models.IntegerField(blank=True, help_text='ID de Site24x7', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text="ID numérico del cliente (campo 'N' de la API)", unique=True)),
                ('name', models.CharField(help_text="Nombre del cliente (campo 'Nombre' de la API)", max_length=255)),
                ('email', models.EmailField(help_text="Email del cliente (campo 'Email' de la API)", max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text="Teléfono del cliente (campo 'Telefono' de la API)", max_length=50, null=True)),
                ('telegram_id', models.CharField(blank=True, help_text="ID de Telegram del cliente (campo 'Telegram' de la API)", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Usuario Django vinculado a este cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_client_profile', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Empresa a la que pertenece el cliente', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
