# Generated by Django 5.2.7 on 2025-10-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='alarms_one_id',
            field=models.TextField(blank=True, help_text='ID de AlarmsOne', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logs360siem_id',
            field=models.TextField(blank=True, help_text='ID de Logs360SIEM', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='site24x7_id',
            field=models.TextField(blank=True, help_text='ID de Site24x7', null=True),
        ),
    ]
