# Generated by Django 5.2.7 on 2025-11-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='Alarma_Telegram',
            field=models.BooleanField(default=False, help_text='Notificar por Telegram'),
        ),
    ]
