# Generated by Django 5.2.7 on 2025-11-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantuser_alarma_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='Alarma_Correo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='Alarma_Telefono',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='Alarma_Telegram',
            field=models.BooleanField(default=False),
        ),
    ]
