# Generated by Django 5.2.7 on 2025-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_fix_missing_alarm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
