# Generated by Django 5.2.7 on 2025-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantuser_hora_fin_tenantuser_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='api_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(help_text='ID numérico del cliente proveniente del webhook (API externa)', primary_key=True, serialize=False),
        ),
    ]
