# Generated by Django 5.2.7 on 2025-11-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_fix_client_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='id',
            field=models.IntegerField(help_text='ID sincronizado con Client.id (proveniente del webhook)', primary_key=True, serialize=False),
        ),
    ]
