# Generated by Django 5.2.7 on 2025-11-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_tenantuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='tenantuser',
            name='user_permissions',
        ),
    ]
