# Generated by Django 5.2.7 on 2025-11-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_remove_tenantuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='chat_id',
            field=models.BigIntegerField(blank=True, help_text='Identificador del chat de Telegram para notificaciones', null=True),
        ),
    ]
