# Generated by Django 5.2.7 on 2025-11-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenantuser_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='chat_id',
        ),
    ]
