# Generated by Django 5.2.7 on 2025-11-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenantuser_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Chat_ID', models.BigIntegerField(db_column='Chat_ID')),
            ],
            options={
                'db_table': 'telegram.solicitudes',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='tenantuser',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Identificador del chat de Telegram', null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
