# Generated by Django 5.2.7 on 2025-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_solicitud_remove_tenantuser_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Identificador del chat de Telegram (texto o numérico)', max_length=100, null=True),
        ),
    ]
