# Generated by Django 5.2.7 on 2025-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_tenantuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='site24x7_dashboard_url',
            field=models.URLField(blank=True, help_text='URL pública del dashboard Site24x7 (iframe)', null=True),
        ),
    ]
