# Generated by Django 5.2.7 on 2025-12-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_site24x7_dashboard_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='site24x7_user_group',
            field=models.CharField(blank=True, help_text="ID del grupo de usuario en Site24x7 (primer elemento de 'user_groups')", max_length=50, null=True),
        ),
    ]
