# Generated by Django 5.2.7 on 2025-12-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_client_site24x7_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCredentials',
            fields=[
                ('tenant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tenant_name', models.TextField(unique=True)),
                ('alarms_one_id', models.TextField(blank=True, null=True)),
                ('logs360siem_id', models.TextField(blank=True, null=True)),
                ('site24x7_id', models.TextField(blank=True, null=True)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('first_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant credentials',
                'verbose_name_plural': 'Tenant credentials',
                'db_table': 'agent"."tenant_credentials',
                'managed': False,
            },
        ),
    ]
