# Generated by Django 5.2.7 on 2025-12-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_tenantcredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='site24x7_user_group',
        ),
        migrations.CreateModel(
            name='TenantDashboardEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_url', models.URLField(help_text='URL pública del dashboard a embeber en un iframe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(help_text='Empresa a la que pertenece este iframe', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_iframe', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Iframe de dashboard por tenant',
                'verbose_name_plural': 'Iframes de dashboard por tenant',
            },
        ),
    ]
