# Generated by Django 5.2.7 on 2025-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_remove_client_site24x7_user_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdashboardembed',
            name='tenant_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Nombre del tenant en el momento de guardar el registro', max_length=255),
        ),
    ]
