# Generated by Django 5.2.7 on 2025-12-11 13:24

import django.db.models.deletion
import tenants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_tenantdashboardembed_tenant_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantdashboardembed',
            options={'verbose_name': 'Site 24x7 Iframe', 'verbose_name_plural': 'Site 24x7 Iframe'},
        ),
        migrations.CreateModel(
            name='NotificationChannelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.JSONField(default=tenants.models.default_severity)),
                ('correo', models.JSONField(default=tenants.models.default_severity)),
                ('telegram', models.JSONField(default=tenants.models.default_severity)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
