# Generated by Django 5.2.7 on 2025-12-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_alter_tenantdashboardembed_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE public.tenants_notificationchannelpreference
                SET SCHEMA agent;
            """,
            reverse_sql="""
                ALTER TABLE agent.tenants_notificationchannelpreference
                SET SCHEMA public;
            """,
        ),
    ]
