# Generated by Django 5.2.7 on 2025-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_alter_notificationchannelpreference_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationchannelpreference',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='phone',
            field=models.CharField(blank=True, help_text="Teléfono del cliente (campo 'Telefono' de la API)", max_length=50, null=True),
        ),
    ]
