# Generated by Django 5.2.7 on 2025-12-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_alter_notificationchannelpreference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificationchannelpreference',
            table='agent"."tenants_notificationchannelpreference',
        ),
    ]
