# Generated by Django 5.2.7 on 2025-12-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_alter_notificationchannelpreference_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='eventos_diarios',
            field=models.TextField(blank=True, help_text='Identificador/flag de Eventos diarios', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='microsoft365',
            field=models.TextField(blank=True, help_text='Identificador/flag de Microsoft 365', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='networks',
            field=models.TextField(blank=True, help_text='Identificador/flag de Networks', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='threat_analytics',
            field=models.TextField(blank=True, help_text='Identificador/flag de Threat Analytics', null=True),
        ),
    ]
