# Generated by Django 5.2.7 on 2025-12-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_tenant_eventos_diarios_tenant_microsoft365_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='eventos_diarios',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='microsoft365',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='networks',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='site24x7_dashboard_url',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='threat_analytics',
        ),
    ]
