# Generated by Django 5.2.7 on 2025-12-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_remove_tenant_eventos_diarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdashboardembed',
            name='eventos_diarios',
            field=models.URLField(blank=True, help_text='URL pública (iframe) para Eventos Diarios', null=True),
        ),
        migrations.AddField(
            model_name='tenantdashboardembed',
            name='microsoft365',
            field=models.URLField(blank=True, help_text='URL pública (iframe) para Microsoft 365', null=True),
        ),
        migrations.AddField(
            model_name='tenantdashboardembed',
            name='networks',
            field=models.URLField(blank=True, help_text='URL pública (iframe) para Networks', null=True),
        ),
        migrations.AddField(
            model_name='tenantdashboardembed',
            name='threat_analytics',
            field=models.URLField(blank=True, help_text='URL pública (iframe) para Threat Analytics', null=True),
        ),
    ]
