# Generated by Django 5.2.7 on 2025-12-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_tenantdashboardembed_eventos_diarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdashboardembed',
            name='microsoft365',
            field=models.TextField(blank=True, null=True),
        ),
    ]
