# Generated by Django 5.2.7 on 2025-12-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_alter_tenantdashboardembed_microsoft365'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdashboardembed',
            name='eventos_diarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantdashboardembed',
            name='networks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantdashboardembed',
            name='threat_analytics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
