# Generated by Django 5.2.7 on 2026-01-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0029_alter_tenantdashboardembed_eventos_diarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants_contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField()),
                ('contract_id', models.CharField(max_length=50)),
                ('contract_name', models.CharField(max_length=255)),
                ('support_plan', models.CharField(max_length=255)),
                ('support_plan_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=255)),
                ('serviceplan_id', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=50)),
                ('account_ciid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"agent"."tenants_contracts"',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
