# Generated by Django 5.2.7 on 2026-01-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0030_tenants_contracts_tenant_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenants_contracts',
            options={'managed': False, 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
    ]
