# Generated by Django 5.2.7 on 2025-10-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertid', models.CharField(help_text='ID único de la alarma (alertid) proveniente de la API', max_length=255, unique=True)),
                ('event_time', models.DateTimeField(blank=True, help_text='Fecha y hora del evento (convertido a America/Santiago)', null=True)),
                ('tags', models.TextField(blank=True, help_text='Tags de AOTAGS, formateados y separados por comas')),
                ('severity', models.CharField(blank=True, max_length=100)),
                ('device_name', models.CharField(blank=True, help_text='Extraído del mensaje (msg_device_name)', max_length=255)),
                ('action', models.TextField(blank=True)),
                ('actions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
    ]
