# Generated by Django 5.2.7 on 2025-10-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inyeccion_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='msg_severity',
            field=models.CharField(blank=True, help_text='Severidad derivada desde message/log_details', max_length=100),
        ),
    ]
