# Generated by Django 5.2.7 on 2025-10-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inyeccion_api', '0002_alarm_msg_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='msg_level',
            field=models.CharField(blank=True, help_text='Nivel extraído desde message/log_details', max_length=100),
        ),
        migrations.AddField(
            model_name='alarm',
            name='msg_log_description',
            field=models.TextField(blank=True, help_text='Descripción de log extraída desde message/log_details'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='msg_subtype',
            field=models.CharField(blank=True, help_text='Subtipo extraído desde message/log_details', max_length=100),
        ),
    ]
