# Generated by Django 5.2.7 on 2025-10-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inyeccion_api', '0003_alarm_msg_level_alarm_msg_log_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='msg_level',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='msg_log_description',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='msg_subtype',
        ),
        migrations.AddField(
            model_name='alarm',
            name='level',
            field=models.CharField(blank=True, help_text='Level extraído de message/log_details', max_length=100),
        ),
        migrations.AddField(
            model_name='alarm',
            name='log_description',
            field=models.TextField(blank=True, help_text='Log Description extraído de message/log_details'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='subtype',
            field=models.CharField(blank=True, help_text='Subtype extraído de message/log_details', max_length=100),
        ),
    ]
